# Site settings
title: "Głównie JavaScript"
email: "jcubic@jcubic.pl"
twitter: "jcubic"
description: "Blog Głównie JavaScript - informacje najczęściej na temat Front-Endu, głównie o języku JavaScript, ale także na temat nowych api HTML5 czy CSS."
baseurl: ""
url: "https://jcubic.pl"
source_url: "https://github.com/jcubic/jcubic.pl/blob/master/"

logo:
  url: "/img/logo-glownie-javascript.png"

include:
    -
        .htaccess

exclude: [README.md, Gemfile, Gemfile.lock, Makefile, clean, date, vendor]

image:
  url: "/img/background.jpg"
  width: 1920
  height: 591

users:
    jcubic:
        url: "https://jakub.jankiewicz.org/pl/"
        name: "Jakub T. Jankiewicz"
        job: "Senior Front-End Developer"
        alternative: "jcubic"
        twitter: "jcubic"
        ld:
          "@type": "Person"
          url: "https://jakub.jankiewicz.org/pl/"
          name: "Jakub T. Jankiewicz"
          givenName: "Jakub"
          familyName: "Jankiewicz"
          additionalName: "T."
          alternateName: "jcubic"
          image: "https://live.staticflickr.com/65535/50132910231_73d867794f_k_d.jpg"
          gender: "https://schema.org/Male"
          jobTitle: "Senior Front-End Developer"
          sameAs:
            - "https://twitter.com/jcubic"
            - "https://pinterest.com/jcubic/"
            - "https://www.instagram.com/jcubic/"
            - "https://www.facebook.com/jcubic/"
            - "https://www.linkedin.com/in/jakubjankiewicz/"
            - "https://github.com/jcubic"
            - "https://profiles.wordpress.org/jcubic/"
            - "https://codepen.io/jcubic/"
            - "https://stackoverflow.com/users/387194/jcubic"
            - "https://www.deviantart.com/jcubic/"
            - "https://www.behance.net/jcubic"
            - "https://www.flickr.com/photos/jcubic"
            - "https://www.reddit.com/user/jcubic"
            - "https://dribbble.com/jcubic"
            - "https://www.freecodecamp.org/news/author/jcubic/"
            - "https://bulldogjob.pl/readme/authors/jakub-t-jankiewicz"
            - "https://dev.to/jcubic"
            - "https://hackernoon.com/u/jcubic"
          knowsAbout:
            - "Front-End"
            - "JavaScript"
            - "NodeJS"
            - "Python"
            - "R"
            - "PHP"
            - "TypeScript"
            - "React"
            - "ReactNative"
            - "Redux"
            - "Prisma"
            - "Eleventy"
            - "Bash"
            - "SVG"
            - "CSS"
            - "Shiny"
            - "Jekyll"
            - "GIT"
            - "GNU Emacs"
            - "GNU/Linux"
            - "Inkscape"
            - "SQL"
            - "SQLite"
            - "MySQL"
            - "SEO"
            - "Graphic Design"
            - "Security"
            - "lisp"
            - "scheme"
            - "programming"
            - "software development"
            - "Web Development"
            - "Photography"
          knowsLanguage:
            - "en-US"
            - "en-GB"
            - "pl-PL"
    mateuszmazurek:
        name: "Mateusz Mazurek"
        url: "https://mateuszmazurek.pl/"
        ld:
          "@type": "Person"
          url: "https://mateuszmazurek.pl/"
          name: "Mateusz Mazurek"
          givenName: "Mateusz"
          familyName: "Mazurek"
    magda:
        url: "http://www.frontend-con.io/"
        name: "Magda Kulczycka"
        ld:
          "@type": "Person"
          name: "Magda Kulczycka"
    inga:
        name: "Inga Durew"
        ld:
          "@type": "Person"
          name: "Magda Kulczycka"
    magda_s:
        name: "Magda Sujka"
        ld:
          "@type": "Person"
          name: "Magda Sujka"
    szymon_s:
        name: "Szymon Spychała"
        url: "https://carted.pl/"
        ld:
            "@type": "Person"
            name: "Szymon Spychała"
    adam_w:
         name: "Adam Wyzujak"
         ld:
             "@type": "Person"
             name: "Adam Wyzujak"
    adam_b:
         name: "Adam Blok"
         url: "https://ping.pl/kontakt"
         ld:
             "@type": "Person"
             name: "Adam Blok"
    it-man:
         name: "IT Manager"
    asnyk:
         name: "Karol Asnyk"
    ag:
         name: "ag-notebooki"
         url: "https://www.ag.pl/"
    paczek:
         name: "Andrzej Pączyński"
    anon:
         name: "Anonymous"

links:

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

sitemap:
  lastmod: 2024-07-17 19:31:46+0200

paginate: 10
paginate_path: "/page:num"
tag_sitemap_layout: tag_sitemap
tag_page_layout: tag_page
tag_page_dir: tag
tag_sitemap_name: "tag_sitemap.xml"
tag_sitemap_dir: .
tag_permalink_style: pretty

# Build settings
markdown: kramdown

highlighter: pygments
permalink: /:year/:month/:title.html
kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes:  ["rsquo", "rsquo", "bdquo", "rdquo"]
plugins: [jekyll-paginate]
